name: Node.js CI/CD

on:
  push:
    branches:
      - main  # or master or whichever branch you prefer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js with cache
      uses: actions/setup-node@v3
      with:
        node-version: '18' # or your preferred version
        cache: 'npm'  # This will cache the npm dependencies
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          if [ ! -d "tradebot" ]; then
            git clone YOUR_GITHUB_REPO_URL tradebot
          fi
          cd tradebot
          git pull origin main
          npm install --production
          npm run build
          pm2 restart all  # If you're using PM2 or similar to keep your app running
